//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotFarm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3724")]
        public int Port {
            get {
                return ((int)(this["Port"]));
            }
            set {
                this["Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string Hostname {
            get {
                return ((string)(this["Hostname"]));
            }
            set {
                this["Hostname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RealmID {
            get {
                return ((int)(this["RealmID"]));
            }
            set {
                this["RealmID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RandomBots {
            get {
                return ((bool)(this["RandomBots"]));
            }
            set {
                this["RandomBots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int MaxBotsCount {
            get {
                return ((int)(this["MaxBotsCount"]));
            }
            set {
                this["MaxBotsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int MinBotsCount {
            get {
                return ((int)(this["MinBotsCount"]));
            }
            set {
                this["MinBotsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string MMAPsFolderPath {
            get {
                return ((string)(this["MMAPsFolderPath"]));
            }
            set {
                this["MMAPsFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string VMAPsFolderPath {
            get {
                return ((string)(this["VMAPsFolderPath"]));
            }
            set {
                this["VMAPsFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string MAPsFolderPath {
            get {
                return ((string)(this["MAPsFolderPath"]));
            }
            set {
                this["MAPsFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("                    <ArrayOfBotBehaviorSettings xmlns:xsd=\"http://www.w3.org/2001" +
            "/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n             " +
            "           <BotBehaviorSettings>\n                          <Name>Default</Name>\n" +
            "                          <Probability>100</Probability>\n                       " +
            "   <AutoAcceptGroupInvites>true</AutoAcceptGroupInvites>\n                       " +
            "   <AutoAcceptResurrectRequests>true</AutoAcceptResurrectRequests>\n             " +
            "             <AutoResurrect>true</AutoResurrect>\n                          <Begg" +
            "er>false</Begger>\n                          <FollowGroupLeader>true</FollowGroup" +
            "Leader>\n                          <Explorer>false</Explorer>\n                   " +
            "     </BotBehaviorSettings>\n                        <BotBehaviorSettings>\n      " +
            "                    <Name>Begger</Name>\n                          <Probability>0" +
            "</Probability>\n                          <AutoAcceptGroupInvites>false</AutoAcce" +
            "ptGroupInvites>\n                          <AutoAcceptResurrectRequests>false</Au" +
            "toAcceptResurrectRequests>\n                          <AutoResurrect>true</AutoRe" +
            "surrect>\n                          <Begger>true</Begger>\n                       " +
            "   <FollowGroupLeader>false</FollowGroupLeader>\n                          <Explo" +
            "rer>false</Explorer>\n                        </BotBehaviorSettings>\n            " +
            "            <BotBehaviorSettings>\n                          <Name>Explorer</Name" +
            ">\n                          <Probability>0</Probability>\n                       " +
            "   <AutoAcceptGroupInvites>false</AutoAcceptGroupInvites>\n                      " +
            "    <AutoAcceptResurrectRequests>false</AutoAcceptResurrectRequests>\n           " +
            "               <AutoResurrect>true</AutoResurrect>\n                          <Be" +
            "gger>false</Begger>\n                          <FollowGroupLeader>false</FollowGr" +
            "oupLeader>\n                          <Explorer>true</Explorer>\n                 " +
            "       </BotBehaviorSettings>\n                    </ArrayOfBotBehaviorSettings>")]
        public BotFarm.BotBehaviorSettings[] Behaviors {
            get {
                return ((BotFarm.BotBehaviorSettings[])(this["Behaviors"]));
            }
            set {
                this["Behaviors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\")]
        public string DBCsFolderPath {
            get {
                return ((string)(this["DBCsFolderPath"]));
            }
            set {
                this["DBCsFolderPath"] = value;
            }
        }
    }
}
